# Generated by Django 5.2.4 on 2025-07-09 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='usuario',
        ),
    ]
