# Generated by Django 5.2.4 on 2025-07-11 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cpf',
            new_name='CPF',
        ),
    ]
