# Generated by Django 5.2.4 on 2025-07-13 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_cpf_cliente_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='CPF',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='contato',
            new_name='telefone',
        ),
    ]
