# Generated by Django 5.2.4 on 2025-07-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdrive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdrive',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], max_length=20),
        ),
    ]
